# Generated by Django 4.1.1 on 2022-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('drive_name', models.CharField(max_length=100)),
                ('driver_contact', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
