# Generated by Django 4.1.1 on 2022-09-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_alter_routeinfo_start_time'),
        ('mainapp', '0002_consumeruser_alter_transportuser_contact_number'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.routeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.consumeruser')),
            ],
        ),
        migrations.DeleteModel(
            name='BusInfo',
        ),
    ]
