# Generated by Django 4.1.1 on 2022-09-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_numberofpassenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberOfPassenger',
        ),
    ]
