# Generated by Django 4.1.1 on 2022-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_businfo_delete_transportuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
