# Generated by Django 4.1.1 on 2022-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_businfo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_Number', models.IntegerField()),
                ('label', models.CharField(choices=[('Tilagor', 'Tilagor'), ('Balucor', 'Balucor'), ('Eidgah', 'Eidgah'), ('Electric Supply', 'Electric Supply'), ('Amberkhana', 'Amberkhana'), ('Subid Bazar', 'Subid Bazar'), ('Madina Market', 'Madina Market'), ('Akhalia', 'Akhalia'), ('Sust Gate', 'Sust Gate'), ('Temukhi', 'Temukhi'), ('Kamal Bazar', 'Kamal Bazar'), ('Surma Tower', 'Surma Tower'), ('Lamabazar', 'Lamabazar'), ('Rikabi Bazar', 'Rikabi Bazar'), ('Humayun Cattar', 'Humayun Cattar'), ('Sibgonj', 'Sibgonj')], default='Tilagor', max_length=20)),
                ('lattitude', models.FloatField()),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
