# Generated by Django 4.1.1 on 2022-09-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_consumeruser_alter_transportuser_contact_number'),
        ('transport', '0004_routeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTransportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('BBA', 'BBA'), ('Law', 'Law'), ('Architecture', 'Architecture'), ('English', 'English')], default='CSE', max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('user_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.transportuser')),
            ],
        ),
    ]
