# Generated by Django 4.1.1 on 2022-09-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_consumeruser_alter_transportuser_contact_number'),
        ('transport', '0009_alter_updatetransportprofile_user_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatestudentprofile',
            name='user_consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.consumeruser'),
        ),
        migrations.AlterField(
            model_name='updatetransportprofile',
            name='user_transport',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.consumeruser'),
        ),
    ]
