# Generated by Django 4.1.1 on 2022-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_updatestudentprofile_user_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinfo',
            name='start_time',
            field=models.CharField(choices=[('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM')], default='8 AM', max_length=20),
        ),
    ]
