# Generated by Django 4.1.1 on 2022-09-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_consumeruser_alter_transportuser_contact_number'),
        ('transport', '0011_alter_routeinfo_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMeessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.consumeruser')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.routeinfo')),
            ],
        ),
    ]
