# Generated by Django 4.1.1 on 2022-09-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_sendmeessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='Student', max_length=20)),
                ('numberofpass', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('mainslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_view', to='transport.routeinfo')),
            ],
        ),
    ]
